traefik:
  globalArguments:
    - "--global.sendanonymoususage=false"
    - "--global.checknewversion=false"

  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--log.level=INFO"
    - "--log.format=json"
    - "--accesslog.format=json"
    - "--accesslog=true"
    - "--accesslog.filePath=/var/log/traefik/access.log"

  deployment:
    enabled: true
    replicas: 1
    annotations: {}
    podAnnotations: {}
    additionalContainers: []
    initContainers: []

  ports:
    web:
      redirectTo:
        port: websecure
        priority: 10
    websecure:
      http3: 
        enabled: true
      advertisedPort: 443
      tls:
        enabled: true
    unifi-inform:
      port: 8080
      exposedPort: 8080
      protocol: TCP
    unifi-stun:
      port: 3478
      exposedPort: 3478
      protocol: UDP
    unifi-discovery:
      port: 10001
      exposedPort: 10001
      protocol: UDP
        
  ingressRoute:
    dashboard:
      enabled: false

  providers:
    kubernetesCRD:
      enabled: true
      ingressClass: traefik-external
      allowExternalNameServices: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: false

  rbac:
    enabled: true

  service:
    enabled: true
    type: LoadBalancer
    annotations: {}
    labels: {}
    loadBalancerSourceRanges: []
    externalIPs: []