ingressClassName: traefik
service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allocate: "yes"
    metallb.universe.tf/address-pool: default
  port: 80
  targetPort: 80
tls:
  certManager:
    enable: true
    email: developer.jacksondroid@gmail.com
    clusterIssuer: letsencrypt-prod
    acme:
      http01:
        ingressClass: traefik
        domains:
          - newlinkedlist.site
traefik:
  ingressRoute:
    dashboard:
      enabled: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  host: newlinkedlist.site
  paths:
    - path: /
      backend:
        service:
          name: traefik
          port:
            number: 8080