kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      scrapeConfigSelector:
        matchLabels:
          prometheus: system-monitoring-prometheus
      resources:
        requests:
          memory: 512Mi
        limits:
          memory: 1Gi
    # scrape_configs:
    #   - job_name: 'traefik'
    #     static_configs:
    #       - targets: ['traefik-argo-metrics.traefik:9100']

  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 512Mi

  prometheusOperator:
    prometheusOperatorSpec:
      scrapeConfigSelector:
        matchLabels:
          prometheus: system-monitoring-prometheus
      resources:
        requests:
          memory: 128Mi
        limits:
          memory: 256Mi

  grafana:
    enabled: false