kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      scrapeConfigSelector:
        matchLabels:
          prometheus: system-monitoring-prometheus
      resources:
        requests:
          memory: 512Mi
        limits:
          memory: 1Gi

  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 512Mi

  prometheusOperator:
    prometheusOperatorSpec:
      scrapeConfigSelector:
        matchLabels:
          prometheus: system-monitoring-prometheus
      resources:
        requests:
          memory: 128Mi
        limits:
          memory: 256Mi

  grafana:
    enabled: false