apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-dev-data
  namespace: webapps
  labels:
    app: pgadmin-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi