---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: johnmartinjackson-com-production
    namespace: webapps
spec:
    secretName: johnmartinjackson-com-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: "*.johnmartinjackson.com"
    dnsNames:
    - "johnmartinjackson.com"
    - "*.johnmartinjackson.com"
