apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: observe
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.newlinkedlist.com`)
      kind: Rule
      services:
        - name: observeability-grafana
          port: 80
  tls:
    secretName: grafana-newlinkedlist-com-staging-tls