loki-stack:
  loki:
    enabled: true
    size: 10Gi
    auth_enabled: false
    image:
      tag: 2.9.3
    persistence:
      enabled: true
      storageClassName: local-path
      size: 5Gi
    query_scheduler:
      max_outstanding_requests_per_tenant: 4096
    frontend:
      max_outstanding_per_tenant: 4096
    query_range:
      parallelise_shardable_queries: true
    limits_config:
      split_queries_by_interval: 15m
      max_query_parallelism: 32
  promtail:
    enabled: true
    config:
      clients:
        - url: http://observeability-loki:3100/loki/api/v1/push
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
          enabled: false
    server:
      persistentVolume:
        enabled: false
  grafana:
    enabled: true
    sidecar:
      datasources:
        enabled: true
grafana-agent:
  agent:
    # -- Mode to run Grafana Agent in. Can be "flow" or "static".
    mode: 'flow'
    configMap:
      # -- Create a new ConfigMap for the config file.
      create: true
      # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
      content: |
        
        logging {
          level  = "info"
          format = "logfmt"
        }

        loki.source.kubernetes_events "events" {
          log_format = "json"
          forward_to = [loki.write.loki_endpoint.receiver]
        }

        loki.write "loki_endpoint" {
          endpoint {
            url = "http://observeability-loki:3100/loki/api/v1/push"
          }
        }