loki-stack:
  loki:
    enabled: true
    size: 1Gi
    auth_enabled: false
  promtail:
    enabled: true
    config:
      clients:
        - url: http://observeability-loki:3100/loki/api/v1/push
  grafana:
    enabled: true
    additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://observeability-loki.observe.svc.cluster.local:3100
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: 'X-Scope-OrgID'
      secureJsonData:
        httpHeaderValue1: 'empty'
    sidecar:
      datasources:
        enabled: true
grafana-agent:
  agent:
    # -- Mode to run Grafana Agent in. Can be "flow" or "static".
    mode: 'flow'
    configMap:
      # -- Create a new ConfigMap for the config file.
      create: true
      # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
      content: |
        
        logging {
          level  = "info"
          format = "logfmt"
        }

        loki.source.kubernetes_events "events" {
          log_format = "json"
          forward_to = [loki.write.loki_endpoint.receiver]
        }

        loki.write "loki_endpoint" {
          endpoint {
            url = "http://observeability-loki:3100/loki/api/v1/push"
          }
        }