loki-stack:
  grafana:
    enabled: true
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume: 
        enabled: false
      server:
        persistentVolume:
          enabled: false
  loki:
    persistence:
      enabled: true
      storageClassName: local-path
      size: 8Gi