apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: express-example
  namespace: webapps
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`express-example.newlinkedlist.com`)
      kind: Rule
      services:
        - name: express-example
          port: 3000
  tls:
    secretName: express-example-newlinkedlist-com-staging-tls