apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: discovery-ingress
  namespace: unifi
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - unifi-discovery
  routes:
  - services:
    - name: unifi-discovery
      port: 10001