# apiVersion: traefik.io/v1alpha1
# kind: IngressRouteTCP
# metadata:
#   name: inform-ingress-com
#   namespace: unifi
#   annotations: 
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - unifi-inform
#   routes:
#   - match: HostSNI(`unifi.newlinkedlist.com:8080`)
#     services:
#     - name: unifi-controller
#       port: 8080
#       nativeLB: false
#   tls:
#     secretName: unifi-newlinkedlist-com-production-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: inform-ingress-test
  namespace: unifi
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - unifi-inform
  routes:
  - match: HostSNI(`*`)
    services:
    - name: unifi-controller
