# apiVersion: traefik.io/v1alpha1
# kind: IngressRouteTCP
# metadata:
#   name: unifi-inform-ingress-com
#   namespace: unifi
#   annotations: 
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - unifi-inform
#   routes:
#   - match: HostSNI(`newlinkedlist.com:8080`)
#     services:
#     - name: unifi-controller-tcp
#       port: 8080
#   tls:
#     secretName: unifi-newlinkedlist-com-production-tls