apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: controller-com
  namespace: unifi
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.newlinkedlist.com`)
      kind: Rule
      services:
        - name: unifi-gui
          port: 8443
          serversTransport: no-verify-tls
          scheme: https
  tls:
    secretName: unifi-newlinkedlist-com-production-tls