apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: storyboard-com
  namespace: webapps
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`thestoryboardrss.newlinkedlist.com`)
      kind: Rule
      services:
        - name: storyboard
          port: {{ .Values.port }}
  tls:
    secretName: thestoryboardrss-newlinkedlist-com-production-tls