---
apiVersion: v1
kind: Service
metadata:
  name: storyboard
  namespace: webapps
spec:
  selector:
    app: storyboard
  ports:
  - name: http
    targetPort: {{ .Values.port }}
    port: {{ .Values.port }}