---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: express-example-newlinkedlist-com-production
    namespace: webapps
spec:
    secretName: express-example-newlinkedlist-com-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: "*.express-example.newlinkedlist.com"
    dnsNames:
    - "express-example.newlinkedlist.com"
    - "*.express-example.newlinkedlist.com"
