---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: express-example-newlinkedlist-uk-staging
    namespace: webapps
spec:
    secretName: express-example-newlinkedlist-uk-staging-tls
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer
    commonName: "*.express-example.newlinkedlist.uk"
    dnsNames:
    - "express-example.newlinkedlist.uk"
    - "*.express-example.newlinkedlist.uk"
