apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: unifi-stun-ingress
  namespace: unifi
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - unifi-stun
  routes:
  - services:
    - name: unifi-controller-udp
      port: 3478