apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-controller
  namespace: unifi
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.newlinkedlist.uk`)
      kind: Rule
      services:
        - name: unifi-controller-tcp
          port: 8443
          serversTransport: no-verify-tls
  tls:
    secretName: unifi-newlinkedlist-uk-staging-tls