apiVersion: v1
kind: ConfigMap
metadata:
  name: biography-config-map
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
        rewrite ^/$ /john-martin-jackson/mj_bio_3.pdf break;
        proxy_set_header Host $http_host;
        proxy_pass http://minio.minio:9000/john-martin-jackson/;
      }
    }