---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: biography
  namespace: webapps
  labels:
    app: biography
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: biography
  template:
    metadata:
      labels:
        app: biography
    spec:
      containers:
      - name: biography
        image: nginx:latest # Replace with your desired Nginx image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: biography-config
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: biography-config
        configMap:
          name: biography-config-map 