apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: biography
  namespace: webapps
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`biography.newlinkedlist.com`)
      kind: Rule
      services:
        - name: biography
          port: 80
  tls:
    secretName: biography-newlinkedlist-com-production-tls