apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: biography
  namespace: webapps
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`biography.newlinkedlist.com`)
      kind: Rule
      services:
        - name: minio.minio
          port: 9000
  tls:
    secretName: biography-newlinkedlist-com-staging-tls