---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: minio-newlinkedlist-uk
    namespace: webapps
spec:
    secretName: minio-newlinkedlist-uk-staging-tls
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer
    commonName: "*.minio.newlinkedlist.uk"
    dnsNames:
    - "minio.newlinkedlist.uk"
    - "*.minio.newlinkedlist.uk"
