---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: grafana-newlinkedlist-com-production
    namespace: observe
spec:
    secretName: grafana-newlinkedlist-com-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: "*.grafana.newlinkedlist.com"
    dnsNames:
    - "grafana.newlinkedlist.com"
    - "*.grafana.newlinkedlist.com"
