apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-api
  namespace: minio
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio.newlinkedlist.com`)
      kind: Rule
      services:
        - name: minio
          port: 9000
  tls:
    secretName: minio-newlinkedlist-com-production-tls