apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio
  namespace: minio
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio.newlinkedlist.uk`)
      kind: Rule
      services:
        - name: minio
          port: 9090
  tls:
    secretName: minio-newlinkedlist-uk-staging-tls