---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    root-password: AgA61NthCimZxv6h49ge/vONGJs+yhtXSl7DxFqkC0Qgh4Iye6e5FgMvlqz0+Kv9ouGAPEqWldsE3HLW/XEkUb4X1DgoqKw4RIzBgT1MYGrBwKGMAluQnOfH2DQ4uYzCWvAo5ma8/ntb/Zj4O663ny91IidD6mZIwnTqNc4XLTfA0A6E/sblZ5pwXteWwvCdZuPSV/edI/7vhZM0pbL06h/GZKiWQ1dqH/bTEyNzxSm3eA5W/8meaPqhWrNdcJj9OMHV5iXwFhDNyyG5QQtVjwA17h7McYn6k+tfNtpxcmkQMN1wws6Pt2vDmJl1c5360X2NRA3FFEMBvVzcH+tnWpbeGuuHQ3zZMV5j2E+I2I6hXXK2IQK9uBZ0FOF2UPD7IGayF4hh0P81wGgYiWPXl1ToCCf8v7GuPVpvcyPMwcJqapzdxK41oBii9zCimJ73SpkB9EWybEVa16V0irfSAhVk/bSRbS6FOv3GVxigiCVJxY9fxuc7OAtj5Ac12szk7bmYUdyBzfIQGIXPktBtJA1zf6yJNUm/rdIbKmsxY6AGELZ0V2CwNJDH/mrvebRd56RL0ThsTAI1HqmtSYY/WBKKF2yS0/LtGcRIbM9SRDwn5SS2y+zEzHRB8zopm05hot0AJig2tnATzhqcgh+3a32z1Xghn2Sr3/x1dtnhzbKgXjm4L2e3gcs6t7YqCjfpiECR4UJIXzssuZ97M6OQc8OpxJ4AVXcu65MwttXewkpgRg/xHvCTmGIj8tlgl38tidtQTxLLId0FFfSL
    root-user: AgAhbkXMpFpzfsT6+k+d8fCiaJo1yyk1oAUZlESpwyI/XIgVP701CkWY/qk6Xm1t98kDQslSe2of5fT7WnqUTgaqk2ZwENovN3TLmNUbXJ/bBPJJ+NHmdjRjBToVFfCJ/cNtgrjaVCv3zDj2Ypr1hNEILf9Cme4DqtgyXDmb05teDk2+vQj7nhdz7Nrq3ItsizD+5t99fiIvCokcvZAA03LevsJodUKU5mPPGeXDPBn0dnVevcx9pnn0HkDwRXRQ1m9y1O4kv0jlp9Jx+jka/16cltU1ELezhmG1JW8o609wg+sAB9ikjFv0cpjM+gDtYN4vpPdS6xeYVfCEIi2gXEL/7Rx9a693ZEV/XxUblRwAnPXxe2T7aX+BMN+RCfnbpmUSM03a9V07Rj4n2uNZcZmegnfNqeTWCwVNBnQEM2zAhW4pT1lqQq6IcXL9/IAPrms4cT0nMDd3KwCeSUUnLP29HTKUg1Jd9PnnEdYb5JGWG0UqcuwPKcsq9QBx3UvIpfVMw9nc2j1su/a3Rh1QPP6fLLSSlvZgtXaBwKXUP7xqJ4Fxzz3a+bulELZ+PK5LhmciAlTPZPpZREjnJWzqxry96gO5yya9evao8CU/jOONwtpab4014BXkN+upX8Gp7WMqh1Sg3jiUzy2OaQebrPp97v9u/9Xe0BnAz4ZoLT6IavBEa3MZYXpucVIo26wSsbhQxPdW7NQgkd/DLw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
    type: Opaque