---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    root-password: AgBVe/wFJkY51xXpAFLXOTl62FF1SX4zk8pEIFOZnlthInUvIV94RWw68PE1SjnAlbyHEeQgI+6lr38HbJu8sXmDxSwSnn3xfYO3ZymPlUJnY1k4o0Mc8ZybpX2pSXifOTLKM4xvARpf3rZp4//OhNZnXCoy0Br/Sbovma14XB5q2dG8j57kXVKAqQ8qS+fQjJXw/KP5gIogi3gvHYk5CEYnr6YOHHTm31IuaSzmmMM5fOsX0mwCsdlp27iamCKsolIEEsp2vVr8Hixd5XEfB+anmhpLuwiWscIgz5HNfPcOgdXUprdBYhHVuHoLZVWMmzbS55hbpnno9yj0nCTfC1jU6mJZBcaRAzysLptLksP5frsb9JdAPRqDWN/CMhZe1SnFCbNf2HSOGfmo4a27KhwCAE2tv+Tp7KZacOryhBWFNwbZW05hPgvU8IrxMzkGxfZphyQm7WHLtDb6i8EWv+XDwi+KGQRYEFjywdRP3NZlcuBMG7imz1mUwjULs2NXk4Fs5/A+PaBNqXvJ0z9Mjf/St4lKFtjPX/MhvpxwX/R30fMhv0mUa4SboJX/POgCoOk6hAaiXIqF8hHHBxFpkU68cKVY3TNowX8NjVX5iwjulMoQAyrulqEvYLGTLDjqKQyMC+OFk8y++++KUF+nua2AJvh/WIm+gFsBSjLsRFAh2O4JU+7MyOi/koRRMRJo4Nm0BI37s+bRb8BTA/DFZbpmVphucA==
    root-user: AgBOjUkJXjeJTsnX2O3ra1rsxr8ZAExx7MAR27itd/KgDNDCGD3MtzSXqRXbiBo0apSORsYLI6Wy9yxdbB+0UN2JrWKK2Pj29k0XcwBVd4EvgIKc36PvXNrLaQeVGsoZg5GfVrdScAGm64nBSQ4RVE+IVvFpsrB4nX7PsleLYMFrnOwT+ExU0p8NZniPVJkdxt5Mj1XHQOdQwp4lpRKn+ULMOYKuYzWQwygoEzFCQbLRbhYt3u0hwCLVU6DHNdGeDHoDkt4WDRhbC4wuWYeMdyAwPED9pyLdBFp/2+39nXmaHOPxUnAF0mlaVHAfWx1hVWApCst5pQ3QXUgKIrTKDdAEh6xANUZvEr9VGCN3orizUbn8fT1RYVOcwxdv6iE8ssqFwKJ7khx4w2VElSgE8/ujZRKnoy6woiEi+ZhLgNLqYL/XUAemQW2JJToPvOFq0Kv1QqkHknSjwXBI+kfKUo/WHYaR6Oxwx5ed+d1DVIu6PNvw/MiW0VsaDZ7l+bypa3Y/Ox98I1RN237mm4kluRzfLvzZw4SzCK815zqkrJTP88uv7tYLH7TDTnJgLJxeBYfIK8YD1QlAJrgHBH75qm/8L2ZxORxftdYIX5SrCq+kuZazlRH/2x0NxbiiJrHA7WTHSG5hs8KTa9v5PWsBCKkcsZrYjtWtgW/GHU665XZFppyhTkXrloBGfQQekKlI0bpvXfY8wqY=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
    type: Opaque