apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    root-password: AgAIJ9e/H4TL+ijVrIZkAjdtJQa3sY/0rRBe84rmFZO8FEfkS9Xbv9DkOs+mmg9wlj4dzVaPJJpNPbyrtWf+cJvk91xFvixH0YQPWfhyKF6aEeRba7stvYiJDlEFrBlLW21d/8J26wiNqUpZmxct+QrGmR2K43AXQJxfWNWoT9TJoV9ZbyTnYRxi3otUDMx+PmIqIrMsAWei+QFh6x1TuSBfIfsZrstCVUXxo4foMue6Yzhpys23H2hkajSG08+W3KqlwRIaPmyErarZe/af8FU32jDnuOdAUArFhxgqjdlIMm+4+JQSCwhZ+k71Vsig0rauzZ27iEEfJkvkzslMPPws1WLBM2WySxRnd7T21takCrVwpA5sUNZRKlcO2B3nlPhtk8FnwWArNmaccg4AIt1URaBJQDYmGEOTqepARHR0CLxq5zGVNQMLJDzXtpC6Pr26wHiRx13zDnDDn6eT/WTjWYTozoAIUejlo7m+JesllUMB7A87oPY0tuUcbDrLw71oJrOlzMhmYKh5MCN6rqrmYaSw+dANgiMwVYtEVcq+y9x/+lgIwoDTCen7yh9GLLhLpyQboMjTB0nCZHmyVfnUEBu+aJfTwOBTbd8zCld+d3+k+lELVhnrSRPZMRIeRzvVOLCU3vklIVR9G4joe1WrWNVKqUocWEbGpEHR3oLYc+7Pcj1mTpR8viSHtfRRKuUPoP4LeQ1Hl/TrV0SDw2oVA+vfax6M
    root-user: AgBlEWOW/FIrRe6hu6rNSoaR1FGAmXuKRfPT3jf7wYfusF/mBrJPO6PzhLP1tiX/uvFo9k/eS7XqsfzO/EsDhEuPhcldC/E3uqsTiygSLVVUlfLqkZ2A45bHcUah9uT3MBW4Ml7wh8TG/njogJa3YoWZH9pUNA8lNIlanY5QA0yhya/37szEgLcUwiLy7+mIZhQ8LKp7as22FfUKm/XPxnTTrP8OM7H2e96VvOpXaSkNYd6kwo85uL2O034jeXInYWhloHAnRQOyZDo+eyhafcsptfMKxIcaG8SBIq6vdNGDGtXyvl4vUcSRumTYi6DjicaNNT9UV7WocBunwT6IkRY8iA226V9sm0wT1OpozT2dGT5g+Wh4Q5bbQF60UDJpgATcbFypHtDrf4JyBDjVE9LiZWIlyx1PWiEHRfp7VvgYl9uW6TelVZRqFmWx2lPmnM5YnzL57JmXQHEJSxg/rjkZ+zZjhbYywKVLNeAxlyFEhh66LF3piIbw/ukyHCpg1XT9lutMYzBgnVXOtpWgM076fTXMrQayM0SHA7NDrFQzXFssA2GPC4Ow1bpgSLaGq95GwK1Esncq/d+V4dQ0MbuKmK4KsmGZLXVr5S+Yyp+YDv02Fkwd/U/2elZPTM6+yaR/KyI6QK0BaKnFlqTK3XuhktmUPbvyrU89hoCNwvtnmfr4HHKluNLEZCJQ+9z1MiaFqrFsmDc=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
    type: Opaque