---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner-secret
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgB3i+tu3FUBki9lIGXNeu+HwI0DKFYRfKqIZd/Wj7O4hHpCGaNZnkAPtXVhAGyiEfsyemkSAANRzuvIv/cOJOgGjSgloDZ9i9AhG4nwKYzrK6K/ufridOzFUz2AEbudlFDULTCpE/nrNGJhOGn697sbguzGtw+b9NVdy2lacjVqxzd2XRBI5qzi/8OtT/DFIecqjiW2jqmXL2F42zTwv6XD65lQvozzDD9DGscpERgc0PgvEqD3C7wfb/vJIf+85S3v9T7U219Qdg6b7aRVeb/OdEBj0MeM2v+297wad7Xip+B2ptH6qcvngBHUQ9xUEfOdj2qUeJlnndjMzP2xxKSEB7XVtVcRPSaJ0/JvwJBNQV5/a9gbPZzX+hRiSWL20oqE/Gtuxbdq0IdRq26FSl9c3UFMMP//JKDvxvOfjTqV7alMb90uqRDXrGUVDZWnF1A27BbG+7jjBElaBChHvYZCbD0PICtQpbQSG7K2THfSXd6PQjtd2+6CEELYd777aDetpYioTzhzjbwS45oBnjpnmXT4HE0SPtWqyqF7emyhEfFhvc0pCNpsDeh4diHRvRhG/2mYAFX+PBMbLxjDe5hqTekNLKm7lunDt5YM6XhG5X0VpP3RWIXi0doNfos4kEhSb5AHvKb34pvu8k4jm/ectx5WDBAQupbhjKkPPJKGlJNt0JOAz+Kf9EtNX59QYyQVMus8m0IpiTJkS70FdGRWCSRGXS1RBlrPg0VhYyS3Zif/oEgmd20hMIvRqgpqEsMUWnroclu+olgFeXKc0Zv2nwxxW1gOfkCg+a8uXlcy
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner-secret
      namespace: gitlab
    type: Opaque