---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner-secret
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgBy+1sY9+Sl3ycUX/pL5Ot/YMtrx+col1E4cClc53WPvc4zr1vgct2lFKHzmLUoi93s1f+2NjCfOgbiRaNSFBuHdG1JIe9ffa+4OBmZk3ETOvr6xgkdmppAxxyrdtUnzNBRVTsahp+6idcA3M+2/UUQYLY6z0gEa+p+SVlnDTBo+GrPBVXJPVI9xLPzN12uGa9ayaWketqN1RYZtKRIR/Hg7n3MM9PPFgNrqMryqrOAWaREJD6E64zjVdZoOh8ObMxpB84TPaxFPviuce86cOYEPnr7mV0mRnaH9AMPHeDQKgM2o3GPKyF/TDm2t35w89kyII00yCgFeYR/7oGkufMqQeczpW7DhktHuo+IJ/JAvNeXHk73j+5Xdgqkkuc9S7xDgQPiKXl8+VMsTZt3SfpPl877AOxtbHkkr62t9sJFxI2yk7cyBtccZTJSbKISCndKK8ncb/uyfzRPX1sO1hGc08xHO7/FlRTd2VvbphBnZpHTEMLVxbLMGTXYRi6syMXy+jiSnfudUP7klis9sFTY0Sp1cbwXEJIApJKXAWKO6wZaLh1ZDPz0Cp/THHqHhkOE97S1JofG9cXmayI2dQWZHptQH/aHgLKK/W7IS3EFUbTisVO6bke1pe/mNQnPBFfi/mKH7+lo53xgrBs/aQgIA2TDRWksV+OOp9F/Yvpz8mspX5Gr3vJj2ctkG5PTjl8iAhzHtwdZ3CE9x42YCj2UrRugAp9Du+ZVaHOlNUpWELz91Fy25lTB+tWlDAlU4sPETMTfVEbALHRyTWaClMlm4D7xiiC9+2B3oYfiabkO
    runner-token: AgAP56ugs4gk8eSWycLZsXz6/aItBDhnodOrStzC+MCnVzx3sR+IgPf8iWXrRRgFoquJAIYLKzOvfwizsuvkdA+J1cYjVjKF3cpssy4Gw8bDc0qt7W36bfbb8BHtkMX7jDcDdxSZScjEUG6FTxa41Zpe1jMrfnJH/t4gLGC+hVhEvxJnxgbSNTKPilGYVO2haM0P7qTuZvcChmBGcUaBAfiJFaqZ+DmZ8g3Ll1orlW9wAesCZlQx6T2VxNkeOsWl9pN2ci0OzqmgL3TLDimtCbqT5K1feJXK9NJ7P4lZSSD28rwZXLy+8gMrDfkXML2sjvZsLHPYqxfSjIaz2+9/81ej7j+DVmmDvuZ4mTKY49G55QL+TWypgHtZKThekJ1Z8e7EyDxmU9lp2v9mI8Nd8KGQNGZ1y+zr6Msa86ctGWDNM/IZLo8WixbFILkWafHlzFe9pFhLqAMCS6UeKWqnqIDa7Iny9g0Ulp/gPWWyjX0XInmA5cwvmvoSY1paEDH9cd1h9Aes4ZHEZiAfp6TQ+Z5Jhp6L47bS6xgYA/MoiTI3yzPjzYJemU5+7tItqNDR5SQzW5f74Ih2awoYcfd9p+/PbTKemNQaFpl7EWehCESU2Bdu9dHw8SGBmb7r08mZe+5Y19TVWZ88fPeDfSa5HboktTP7oGGS9RuekYOwbFZAvz9EaagefnLg/9cyFhTsd/w=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner-secret
      namespace: gitlab
    type: Opaque