---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner-secret
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgBHPt4YwFmRzgS2BbEo6qBDbUQXOhafJl2/vAcbKeHM5m2/aCNw/QZW5OU6DZDiZlB8xE4plC0WDhpmWHXtVmetwjo47H5gpEBlXQywVVOacIOvs27v+GkRvFaEMyNdLd6QEmCbBQZHEEMrLzDYJhw21Et4b8vWM23S7Oy2m4HaTvXRWvX4sUl1W7WrYGn9pO02r4GdC1HUPaLtIxd1VXPF4ss70nF86rjvLIWHMBUUab/GWqnutB2rYhic5VotCwZKDAXeoz5eOrWskZoU6NXR8aHPkS+C8aa458k4jDrzNMVtAtKPoKAyrasE5xWzwK8nFK+rhj9ss88RCq2HMrKeJ41A+knFqJiBDkjaQHls3xxrUKurBVDYM01AMKJ7sSkv7Ut+AtjVhC1PnJuUUxYEsvvqS+Qb1i1nwy9aVP/pk87n7NGiFdkMUi2CRcCReMoYlQnwMIvxkqaCy5kKUzopjSldUgcqeOtcIC+OHPnX7z7+uFzhSuI416Fk5F4HiBMdAts2OES1/dBPyxvWkgPCbVp7DlHA4pvNwF9Ofp8rAfLx03I7smv0kAAF34YdTJ0gCoyeu2mWFMS08ftSULfdZvxMF6ABWxexXfBlrQL7yGiEh1QuTTtocuToDd9nhlEqktAdq7ZPzaiyvlfSh+YNdPhkM/zPd5tSJXEX5RWbQmrK5Zatp6nRRyqOPyAiE1ltw2oOO7jYmQbBY2j3zuokCQ+DsI4FUgqbhSTD1vyK2v1KTucP3PR5Jce/yFaQfJp842oa7zpFtmAE+E16WvOZs6PYTREkZiM+naiVQfi0
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner-secret
      namespace: gitlab
    type: Opaque