apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-dashboard
  namespace: argocd
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.newlinkedlist.uk`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
  tls:
    secretName: argocd-newlinkedlist-uk-production-tls