---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
    namespace: cert-manager
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: developer.jacksondroid@gmail.com
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                    cloudflare:
                        email: jaswahhihi+cloudflare@gmail.com
                        apiTokenSecretRef:
                            name: cloudflare-token-secret
                            key: cloudflare-token
              selector:
                dnsZones:
                    - "newlinkedlist.uk"