---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAjLxjNBH+IGHNb3tWNUYR4kOT026HIU0NihOw/GDhGuolC5BdH43aect5uSNNpYxdAY4sjDtZskDCBht4qPUXroEZOKkBepv51AI5DohgmyT4Pz0gPCPCarH/PswG4RM8FNKaP/ZvrpuK3rIBo/cAIHVrjuTkf3SuKklTT5/3p1VrKBJmTeZH22uf8KI8Njh5AFLDFJOaqwXbn6xh1fseXpDp7222+QdD9cYbgbgJE0wMBbKphcchjAa1QmoMqMfsqA+TDtqyrof0lkSQSccIxbuiXosOYsHby09F9q2b5kHh9Q2BG64TjIDwpsODeQCbOXgM7c3gBrECv6LnzSCduW4Ws2DZq+0pIyDUc68Z03exS/50d8C43yF5QJoaIgTrlkBedwf6+UzblvB8U9KVTnKOYTr6U1vN/TSI/3JFAcJS/Txrfa0KrFjaabODl2jpeiYSvtIgchSXM5XmjXrsOhq1ow/n2Q40j5Aomu6el4rbz46kFPalW/CAEXMpJrXHjroTOYxmthx4oe54c6SO8s0B6ALqoMWkbUyapN+IAMirzYStOwxFr0gYwcnrnMkpDLa4qRC+kPM/zu8V31imBbeSgiwhGsEDPm++PWLnjmiOs/mFG9Md17FJbrcuAM8AIhzt3FJUpzEbCLrEP4XePeyLIUFrHK8AwjC0o5CtLk8QPAyA0NVk+6557p1ZHpgnBIiiHpmPEP/S9Rw93AhYWwu0mIDN1Hi+oC8dTSWsyS+M2n/vzfDBk
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque