---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCj1X8MvbOei9ziZ+RQoOZh//0Ki9a1W9USvtKhBObclXgi735dCDm8zJtuixGk5GlMdsSCU94yXtCaVBNmYN1VI0Jabh6BcJmKjr8/aNmN7dy8opzipQN4SEWK1YxeelAernLiZHbkjaFSrRC6NSAbcJR9r5pFw5TC2lqcbCGQemulu3u7HsNva+cm3jpNw+WdkmNIe1NseOjkMHnYt8vysBFJ0oIJFntfP3vjEAx4Z56EK51ALth7SbtqIHZIkHN71oL1HVhQPJ5bLkXV1Kl01dPG7zrQYjzmrue0WDnheqObSCVSzbugDyjln/XVpoRjm813V7XJecS3XKbT8uqlqN+AJGo6Vxgq6E4aIJIjmKC5uavxrIig5MaXyCkUGyCrcwPQXIMXzv3DXcqykxidmwZ5Gv2v9w6Y4suosNp5VQkdxAxVH4teH1vOoaUKduf4rs8Dm0AW7CtNrUppqGQZ9Y8Unqr3ajHhVRTl3UdoQNMZ4iDN8Ef4fBWyJ+l9/gFHtnJwRFChdrKjlW1EufIKlQIqFMH/c2BAt7oFwvtwKwcXRgMhTjKJeVHCzo624FX2wWaOKm6hQQqjQsYYWhP9nDtB64nrW7mFrAj76Z6M7UKYpRqH9Z20H9Iq2IhGyEX0EAAvxQGz85FpArEvA5eG8ZvCl7CZniXAH5GrHjYdJCLmppQbdq0VHaAG/JZ+zrDFQa+EZPtfY0E+8YZgXniI22xuZ6nTmgxcfeJUjsJhPSCvSQg45tn0
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque