---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: prometheus-newlinkedlist-com-production
    namespace: prometheus
spec:
    secretName: prometheus-newlinkedlist-com-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: "*.prometheus.newlinkedlist.com"
    dnsNames:
    - "prometheus.newlinkedlist.com"
    - "*.prometheus.newlinkedlist.com"
