---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bin-day-pete
  namespace: webapps
  labels:
    app: bin-day
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bin-day
  template:
    metadata:
      labels:
        app: bin-day
    spec:
      containers:
      - name: bin-day-pete
        image: jackson147/bin-day:1.0.2
        volumeMounts:
        - name: bin-configs-pete
          mountPath: /configs/
      volumes:
      - name: bin-configs-pete
        secret:
          secretName: bin-day-secret-pete-config