---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bin-day-secret-config
  namespace: webapps
spec:
  encryptedData:
    config.json: AgBJ+JbXvfEHUeYNnEa5n8vimnQpB/VQhs8tfPXAIO5N5EcIP1+NiN6HAym3ZTB/RD1AYBpdESezib988OUfNNx786L7M0yv0liOoUeJtFTZzO6iyBqRzEcZOl49ZNQ8op6tnVoNDPdGym0wP1JiZ5DtWGGYQwKDMDouzh1JQBoprOo8QR7+CBgTeZNkv5E1zcRkCZ8Aspz4cDzNnmvA6njiek7uG6PUdQsa45V4ObbAU1KwhLMv5CP3goifX30ofcY0wuEgW8FZoDvn3xkAtdiu2onInIyURdnEoemNHDCO/4OVoMeuJqpR+i7nLL/0wcG2mEeB6SsvAwbpcf4OygtvlVHQs43XImWd6Q0X/zaJ+6c1dLbVhaToWLA8WfRbQ0W3Y6RyOEdszI9UJJstBX1tHr0trDaJI5bUoKJT2SSnCTWdFD94KIXknGFEu61hH8TAhDnHpptii91/WjoHZVas/HsRYwvnPgq43BXUfbs09AvIY0DXw3A05Ktr/TmHdkADx3MSU6dAyvS9jR/djMvt/QrG0TpXGAz664RoKJkC4Sh1uR557qRkqrQyxtmK6PJjE/KqCpD9pHkZODtgge3DtMZosdzA5s8uNYo1r6RwmCvOTGtJw3uklpzQIoXxH8gObWztzVhaX5sKTILDj9fBCvhOIXNE3JK2w2qcPOA9fVCNaID8a40qnH5y0vBL1SOzDB2sWgHUDTXvh4yGNPBMfeEOJvUX17YM5qxESZUNvWv/ez4RuGc/R1ri786aTnHKo/bb624cmAfyAaihZqE012hI5gfEdOZIXPfvgjqw6voU0cM7MLmU2NTp4MdjMSJGx/OPnIDfqS3wG0AE0lrIMxfjCUq1DCkELx93HtedwgYjXBykj1UoLHkRf4acaJHnkHRppDZb2fzddjf0tnRKSk7z85oWF1GUBXd03rLg1f2MzAcE/B2slslw1FEI3Sswh+OjJAn9fYKlTsIhJkX5RjanwdwQhJAjSaO+tsj0HnsP169XjW9FrBmvJcstDg7Q/61rYydTEho6D7KT6muj4F3PsqtO8IAHw8u5o3eO9t7aCAKkZCHfo1AUSPoS1Ygg1JWqeAqHTsm4p+t0VNtTv1UysaAqXbwlkD0JBXgaak8/9yHBU835DPIfVGu47czQy2YAohI5bONRsEY06D3tLRaxpXRovxjtcW2I0naQGC2xleZGIytEZNLD5uE/+dG//JMr3PdMUrMnYlYGKImmstbLuZdFTdlF789jwF3Ocv5COmWX9Xi3L8m466Z6RSedQIxaz1tsPmsC8WhCroqMOXLCiG3yxofvoXPnsTTe4SGz3mDVLifU0AekLJJCpfGhaXIlRoGb5RqQLn7IuSDHqw8Kz74oBpy5
  template:
    metadata:
      creationTimestamp: null
      name: bin-day-secret-config
      namespace: webapps
    type: Opaque