---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bin-day-secret-config
  namespace: webapps
spec:
  encryptedData:
    config.json: AgCj9vDfqoSo4On3wq7nHDamAaDK1BIQ/EyQYAaIutZtL/kcrrPcZf6woZQOADw5uW3aaa6Vf8/cF4nRQat8xEtQUo3u/n6el20yGHaRmELwvaVQM07faSlF4VpqsPXu4cdgs2Gtex4fZzSHCoyAi8zfmR7xNyOuV6s20w/qG9V4aStLXwlpyFCzv9sNFfACpozczOnuMhe3glN9U0C0uf32rmxa9focgSQQj5mLK9SHVHIVofCSrfHEaTmUyk10EjS/6bU+46Tj1mt84lYWIKTzCx8jESdJRCIdxOTPetySRr5HUO1Wpz87kN6vygI1P5D10ihjPwUY1E1q4jINGQbtTi08CejjpsJaQgwuUmRS5Wii7vipPqGL3p3SInfy+rcR6aFUCstUr2mPCxVuFWCE9GjxNMSDD1MhcAqamr7wt8euISNl8Ku8TS42kL6k1dJMAd3RW52vvR+QnbNM9HCXpyKlOBWolxIyHzvfK+OYeihI1k+ULCCCmobW8GJVdQvDsglKR+cGZEIX1pS7ukaYByWlBqFXmvXbeBMudD4CFpBbTt2rEgsY99vjD7ykat6gbIDVsnajte0l7ov7WNMnS0Nx7d/08b2uhzSTCljcliCXK84EDNmqu84UyNQ1WxebgDJ+0mckbI6XBI9jccu6uNSBudrtIkMd8EUlF0siIaWYCjTnHMyKeQcIG98E4xjQiynJWcI0tk44j8+Vd+5P+ODru+QceKOQbZwyeDpI6hbBLxd/Fvar+iJY5rtVv9n1rWgJCz9Kr3Fv95Q20keHjLOUemN3B4KF8GpVdUVv4P6vCcnD7/hkYdW9GUfJ3gRFXW7SLQjGJ6bVOAdLazGZfbzyzr6RPLrtDrziVro6lMlIdfUGisOKNZS4UGbj2jPRdwAkPfpNe+mV1TRe40I/ihaHP9fKq+YYxYm+NRr1Ezg+H7inSd7LZlwjoYdrK44RoFawotfqisM6ppI8W0VH8vZDMkEQ+qVFTcnQiPVCqlw1Rr6fFkWp931WIO1+k7m3Gaqn2rEKBYEfd5G0Bq1Tu+y7/faeQhtS2WIT0JKCUxu7OPiASDFjG/Xb5bpvfXaKNqKLeVd10qa2KfXcWxgF592Ebo+SB/9/LQhHcYe+4uSfzW1X6pH1QMbGt+qYze99NWX9PXJazr5fpwyygi8FcWZsONhWAKM1Hbopk+AsZOpSODRGPnHHimHhl3ZNJPIu0tfMW4dzmgClmwiSuZ9pRs0sE9Fv4YsfraDBuis0isHqjWDYtPJBnBJSHZL/O2RDcRq0RVcZ9G+3pmDEXo2mxtUVddSl8QumWcS92wdRGrQUoYXrA/BlACQEgbwS0Zb3Shq7UbuEViqgXnSc+0Tq/582Z6/NTfwLfyJc+wQ8c0d7dmm4n4VTsMk87Y0SHasobCmmIbUCrunQqGrcZas9jYfhObdM8Nkf1df00R+m4uVH
  template:
    metadata:
      creationTimestamp: null
      name: bin-day-secret-config
      namespace: webapps
    type: Opaque