---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: unifi-newlinkedlist-com-production
    namespace: unifi
spec:
    secretName: unifi-newlinkedlist-com-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: "*.unifi.newlinkedlist.com"
    dnsNames:
    - "unifi.newlinkedlist.com"
    - "*.unifi.newlinkedlist.com"
