---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: traefik-newlinkedlist-com
    namespace: traefik
spec:
    secretName: traefik-newlinkedlist-com-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: "*.traefik.newlinkedlist.com"
    dnsNames:
    - "traefik.newlinkedlist.com"
    - "*.traefik.newlinkedlist.com"
