apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: argocd-scrape-config
  namespace: prometheus
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - labels:
        job: argocd
      targets:
        - argocd-metrics.argocd:8082