# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: prometheus
#   namespace: prometheus
#   annotations: 
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`prometheus.newlinkedlist.com`)
#       kind: Rule
#       services:
#         - name: prometheus-kube-prometheus-prometheus
#           port: 9090
#   tls:
#     secretName: prometheus-newlinkedlist-com-production-tls