apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio-scrape-config
  namespace: prometheus
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - labels:
        job: minio
      targets:
        - minio.minio:9000
      metrics_path: /minio/v2/metrics/cluster 