---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-arm-runner-secret
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgAXJXKv/gdX1oJEbHSPRSi4IfZs2Ucz3pte7mWEiE5huUhB6LqUmAWK21rQzOvwZzC75PkRP4hJaVVAhQpVFYUkbtrvaEYicpVgdKbLfN5mKiOm7ebpi13mtVdPFdPZfspZEs8V8jTCV26ZXc9zna9nLsVV3hhK3YPj3yClrZwVJSf1HCCOqkid0L70wtb7mN64cJS8RWDnB+OYO1j3gB4XJdMBLNtdlDaCESHWEzKJ3NSdVg2EDNVgpR3kqhfyFY0dmUXy4KG7qSerhk8aiFRNqrjMq4qp5+cnQgzSsjtdUfgWxl4FnFzO/JvkDt4TGvC873EcoUM5TwJ7b9kP8/0IwuwCeXI+h2nbRqdLNdlirfw4Pqp9wGFvCuECw/EdodpUq06BI1RGmNA7nt4cE0jWwSLo2z7Ue3DheUJqGXpLNOPyi/e9uoAafw5jeWYunsAXD3v5atUAlutRmOXZud9iIHe50y2DnSgjG8rB9T6YTLvqJ35r3flVOKjbrh0WxuLpsb3BVPo0kU7Dla1kgv7fKkvfJIk6sdCv6TQQWLYrpl5CPYnb4CyQOAdwgq6FxKXy0mR0ffahul2H1gYWdELOHkpiphqvEoZ3G0YW6OFNjNp/10nCZlAdGP70S6zmtwSraKBDu6gQT6G300HE+DaOdwnclT2oxthYSZRthNyHDUGrSEO7id9yEVkzHtGVGEihvsFJ1cQXZXcpMT5ply73zcvzCQ5dKEtIdH7zOb3Q6S0OxpLQq7BEmqjFhTy5W2+XdDfWSjBRg4QQdRiAAx48GjuqONEXrcfaYgz9A0bX
    runner-token: AgBRva7V6vL0Wsby9N6BHsb9I2uS8Q3nplP0XxW2w8h1k4LH0Zc0MY17wCggb0L0aUCFzoJr75x85ts8+YUkAb57/6POZy/bGnS0O4Tt3VoCPcbMxGq/wqcXP86D5NtgAuuwP0rhvKdgMOAgC/5sAsIw95jJCD6zgV7Q76ZvDRM5v4yEGh/VRqOyk0CGwsp7xVPMPXHwpm8RcKVOiF2SX7WEb2f17Bdgy9bCrV4r3g+F6+4YY1E31TxXSrc/COIa6r2H2DNzi1XZlNh/MsbOvaIsAOtKkWkaXSBc6/BjAtEx2t9VFnzjs3KKGgD5YqNOLjE1jzoZ1b8s59HeBBV44ltraUoIK8H0apzSvPyiy47M83gTPpfdkOSnajX2hMf2Cz158IOM1Y4g32G7ozRk3rCbTkLIBEWcco5bdv3w2BhusYGpQQy9cRkolHxxtsUhhmajf8Yc9oTv0/v+R2Lm6e/iOar19jB/MExSWGrV11TcBM+8780Vz6Uc1nWtGcnddVziQwhzkR05JlxUBcJQLRuvSVxgt9GlnGu9pXPNocm/N0ebJfZ7dg4HGhmKT6K9b+Jt6BBRuJZphLo6Fi1WKGisX8ufgeO/iiDQ0jV4Ih82seTsAKRWAGF7+WlLjYePNTmA83D8aaIrLnPGtvTV20zzlyELllOj/WcKPZjpHynwDCiw22LxoBOCD8k3Axu5hb8=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-arm-runner-secret
      namespace: gitlab
    type: Opaque