---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-arm-runner-secret
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgAXCA2BX69qNBVyuyfVHX4vZ5w+u3LpuWAqva7djqoCR/4V52yEnunCifWhXw7GckzisTJ5jGVkBV/B4oC/GcMfA5L6xXiq6j6BETk4rp+VQY1seVM8tHPtRUbKcfK8pPtzNXuNZkDbdlvdCYnr3JhOsesu5Sf+X0InwBq9MlNn/fZtyWCTjtRsn6Gz0s0J0vvxLL4Ai0oWNKIFZMORf+cltK7/3sB1HiWUnK2npKXiHAjgREVA8Jmfs8I2hSpgwobDI1HXUpTb+jVwiyGGE5Mlj9jadU+2KsVAlgmwLMNgtbCJpSxaefEugLU/1vZIGachCFN+39pHuHQ0xHG0pfLZb/YSz8lPdogtqYpgRt0FW3S8dWJnzUoHi1+ASGE0AWo6T5/v0Hgbsxou9YAV1IoxYhppNYVsHpca/zMNQ7RGbMgcH+Chu9nPNDqLM0kZ8wduvs7Er26Cwj1Mp02/MXdhsrBb8VwiLiPORrTSZISH4lKqC+zFSR0umkynVRNbF0JMqwMKSIMXjQo4k+q5G0dehUAmTj57zSs6tDgkKw3mQmwMZURP1JTWVLNrZnpYku22VQPnh4kBJ8WT+ILYVYmfYUTKzMT2nQZM4Qp49yQQtSKc9tUWxmxSNGZjqnjYaflnx2NzrKWIkWgWmHJtnoWasm1CG3UOdx8SHmCcyjkfkaAHlLNHXFa9N0fx0j67gqfCPeD36kmydjHploqyfR0NvPEA2LXnao9sK4N3O8dcOwAWA0HCXHRfQrL3Mt06O+PL6INb9bvkM4SKW/Mgq8a18Pxkl2puHJgDYMS96FLJ
    runner-token: AgCc+8aKThiUvCED5yS679bGtl04nhCBmkiR5ruVnm9zr/JV2cy5HH6UDC7PDGVAPJ00ys4xAtJRTs7HvlzIRRf9mC2cev9zxspytY86CcTPISfTvsfqLKmpYfvOQJORS9jV/WQGDlEnXaFHqwGcfmHJYpBZRGy5us5e3O2hGSVKZ+qsXPxuR5WXWGBU8z6sgcSyX5QKEuZEsF9pxiH3lqwDms+/mpDwLOI7oVcUIyTLjXOolIVOfuEE0lMYd/70DQv63+3QAFhPzfUXatZ0zayxZYElikma6uvBbg+1XkMRl7ypRxuIT/EXnMpINjx9tkR468ANTjL86XHe7ySH0FslzdgfQ3zqoFeOymShMOXbJ23QwDk+GkZ7g7pjalMn5eDaV19CgFkt5iOYnM4+QfJTbdpdpslf9tOInUOMmhGQ5GJvHxAW5cK4AUreo672aRjlTB1pM+P5L0dEbjJcWenZLSPDB5AD/vPCydQAcCdagIaTEgWVXGwsHvsbZHMfGqTXpaUPbls/KgE22id+qvYcL649vPMZ2WXlykKGbJmPTmvFTR600nDQ/udHWkFnsY/aVYu7inTgJraTx3iWm7Jm+PWt2wpIORjWKy2iZAhkXRVtiqZ+3J2OCUL4Q/RyFOhfVJkBg1/q8/hWgwN2efXTP2wAVklcbUEIsBV/41FcWtQjBbAVU8X+iE2CSwNYmEA=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner-secret
      namespace: gitlab
    type: Opaque