gitlab-runner:
  gitlabUrl: https://gitlab.com/

  runners:
    secret: gitlab-arm-runner-secret
    
    config: |
      [[runners]]
        name = "k3s-arm64-runner"
        executor = "kubernetes"
        # Fixes the long polling warning
        request_concurrency = 4
        [runners.kubernetes]
          image = "docker:24.0.5"
          privileged = true
          namespace = "gitlab"
          [runners.kubernetes.node_selector]
            "kubernetes.io/arch" = "arm64"
          
          cpu_requests = "500m"
          memory_requests = "512Mi"

  nodeSelector:
    kubernetes.io/arch: amd64

  rbac:
    create: true