apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: '2.17.3'
    chart: sealed-secrets
    helm:
      parameters:
        - name: fullnameOverride
          value: sealed-secrets-controller
  destination:
    name: in-cluster
    namespace: kube-system

  syncPolicy:
    automated: {}
