apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storyboard
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jackson147/k8s-testing.git
    targetRevision: HEAD
    path: helm/storyboard-rss
  destination:
    server: https://kubernetes.default.svc
    namespace: webapps

  syncPolicy:
    syncOptions:
    - CreateNameSpace=true

    automated:
      selfHeal: true
      prune: true