apiVersion: traefik.io/v1alpha1
kind: IngressRoute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`*.newlinkedlist.uk`) #Old test domain
      services:
        - name: noop@internal
      middlewares:
        - name: redirect-to-new-domain
          namespace: traefik  # Adjust if your middleware namespace is different