apiVersion: traefik.io/v1alpha1
kind: IngressRoute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`*.newlinkedlist.uk`) #Old test domain
      services:
        - name: my-service  #Dummy service. Not actually used.
          port: 8080 
      middlewares:
        - name: redirect-to-new-domain
          namespace: traefik  # Adjust if your middleware namespace is different