apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-redirect
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`*.newlinkedlist.uk`) #Old test domain
      kind: Rule
      services:
        - name: noop@internal
      middlewares:
        - name: redirect-to-new-domain
          namespace: traefik  # Adjust if your middleware namespace is different