apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-new-domain
  namespace: traefik  # Adjust if your middleware namespace is different
spec:
  redirectScheme:
    scheme: https 
  redirectRegex:
    regex: ^(?:https?:\/\/)?(.*\.newlinkedlist\.uk)(.*)$ 
    replacement: https://$1.newlinkedlist.com$2