---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: traefik-newlinkedlist-uk-staging
    namespace: traefik
spec:
    secretName: traefik-newlinkedlist-uk-staging-tls
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer
    commonName: "*.traefik.newlinkedlist.uk"
    dnsNames:
    - "traefik.newlinkedlist.uk"
    - "*.traefik.newlinkedlist.uk"
